# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, firebase ]
  pull_request:
    branches: [ master, firebase ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: mchirico/gcp-actions@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.OWNER }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud components update --quiet


    # Credentials
    - name: Get and Create Credentials
      run: |
       mkdir -p credentials
       gsutil cp gs://nodesepta/node-starter-mocha/credentials/firebase-adminsdk.json ./credentials/firebase-adminsdk.json


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        npm install
        npm run test
        bash <(curl -s https://codecov.io/bash)
